name: "buf-setup"
description: >
  Install buf for use in other jobs.
branding:
  icon: play
  color: blue
inputs:
  version:
    description: The version of buf to set up.
    required: false
    default: '1.11.0'
  github_token:
    description: The GitHub token to use when making API requests.
    required: false
  buf_user:
    description: The Buf username to use for logging into buf registry.
    required: false
  buf_token:
    description: The Buf token to use for logging into buf registry.
    required: false
runs:
  using: "node16"
  main: "./dist/main.js"
