name: "buf-setup"
description: >
  Install buf for use in other jobs.
branding:
  icon: play
  color: blue
inputs:
  version:
    description: The version of buf to set up.
    required: false
    default: '1.27.2'
  github_token:
    description: The GitHub token to use when making API requests.
    required: false
  buf_user:
    description: The username to use for logging into Buf Schema registry.
    required: false
  buf_api_token:
    description: The API token to use for logging into Buf Schema registry.
    required: false
  buf_domain:
    description: The domain of the Buf Schema Registry to login to.
    required: false
    default: 'buf.build'
runs:
  using: "node16"
  main: "./dist/main.js"
