name: 'buf-setup'
description: >
  Install buf for use in other jobs.
branding:
  icon: play
  color: blue
inputs:
  version:
    description: The version of buf to set up.
    default: '1.0.0-rc12'
  github_token:
    description: The GitHub token to use when making API requests.
runs:
  using: 'node12'
  main: './dist/main.js'
