name: "buf-setup"
description: >
  Install buf for use in other jobs.
branding:
  icon: play
  color: blue
inputs:
  version:
    description: The version of buf to set up.
    required: false
    default: 'v1.10.0'
  github_token:
    description: The GitHub token to use when making API requests.
    required: false
runs:
  using: "node16"
  main: "./dist/main.js"
