name: test
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./ # Run the local version of the action.
        with:
          version: 'latest'
          github_token: ${{ github.token }}
      - run: buf --version
